[package]
name = "venlyn"
version = "0.1.0"
license = "MIT"
authors = ["Azalea Colburn <azaleacolburn@gmail.com>"]
description = "compiler for the venlyn language"
categories = ["compiler"]
readme = "README.md"
repository = "https://github.com/azaleacolburn/venlyn"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
regex = "1.13.1"
strum = "0.28.0"
strum_macros = "0.28.0"
