[workspace]
members = ["lib-venlyn", "lib-venlyn-proc"]

[package]
name = "venlyn"
version = "0.1.0"
license = "MIT"
authors = ["Azalea Colburn <azaleacolburn@gmail.com>"]
description = "compiler for the venlyn language"
categories = ["compiler"]
readme = "README.md"
repository = "https://github.com/azaleacolburn/venlyn"
edition = "2024"

[dependencies]
lib-venlyn = { path = "./lib-venlyn/", version = "0.1.0" }
lib-venlyn-proc = { path = "./lib-venlyn-proc/", version = "0.1.0" }
